[General]
BgSource="/usr/share/sddm/themes/corners/backgrounds/maidkasa.png"
FontFamily="Atkinson Hyperlegible"
FontSize=9
Padding=50
Radius=10
Scale=1

UserPictureEnabled=false
UserBorderWidth=4
UserBorderColor="#C9CED8"
UserColor="#F1F3F7"

InputColor="#111318"
InputTextColor="#E6EAF2"
InputBorderWidth=2
InputBorderColor="#5F6675"

UserPlaceholderText="user"
PassPlaceholderText="password"
HidePassword=true

LoginButtonTextColor="#0D0F14"
LoginButtonText="Login"
LoginButtonColor="#D9DEE8"

PopupColor="#161920"
PopupActiveColor="#C9CED8"
PopupActiveTextColor="#0D0F14"

SessionButtonColor="#2A2F3A"
SessionIconColor="#E6EAF2"

PowerButtonColor="#2A2F3A"
PowerIconColor="#E6EAF2"

DateTimeSpacing=-20

DateColor="#E7EBF2"
DateSize=36
DateIsBold=true
DateOpacity=1.0
DateFormat="dddd, MMMM d"

TimeColor="#FFFFFF"
TimeSize=48
TimeIsBold=true
TimeOpacity=1.0
TimeFormat="hh:mm AP"
