# hyprlang noerror false
# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User

bind = Ctrl+Super, C, exec, chromium # Chromium
bind = Ctrl+Super, O, exec, obsidian # Obsidian
bind = Ctrl+Super, G, exec, cartridges # Cartridges
bind = Ctrl+Super, D, exec, vesktop # Vesktop (Discord Client)

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

