exec-once = solaar --window=hide

input {
    # Teclado com layouts US e BR, alternando com Alt+Shift
    kb_layout = us,br
    kb_options = grp:alt_shift_toggle

    # Desabilitar aceleração do mouse
    accel_profile = flat
    sensitivity = 0.0
}
